version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(actions)"
